# Generated by Django 5.2.13 on 2026-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("finished", "Finished"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="worker_massage",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tasks",
            name="worker_task_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
