# Generated by Django 5.2.13 on 2026-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0002_tasks_rejection_reason_tasks_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterField(
            model_name="tasks",
            name="worker_massage",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
