# Generated by Django 5.2.13 on 2026-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("reader", "Reader"),
                    ("worker", "Worker"),
                ],
                default="reader",
                max_length=64,
            ),
        ),
    ]
